# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-02 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
            ('accounts', '0001_initial'),
            ]

    operations = [
            migrations.CreateModel(
                name='Token',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ],
                ),
            ]
