# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-02 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
            ('accounts', '0002_token'),
            ]

    operations = [
            migrations.AddField(
                model_name='token',
                name='email',
                field=models.EmailField(default='xx@yy.zz', max_length=254),
                preserve_default=False,
                ),
            ]
