# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-02 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
            ('accounts', '0003_token_email'),
            ]

    operations = [
            migrations.AddField(
                model_name='token',
                name='uid',
                field=models.CharField(default='-1', max_length=40),
                preserve_default=False,
                ),
            ]
